baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Simone Simonella | Portfolio'
theme = 'minimal-portfolio'

[params]
  description = "Simone Simonella's portfolio - full-stack web developer"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menus]
  [[menus.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menus.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menus.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3
